--bai8
SELECT KHACHHANG.MAKH ,HOTEN 
FROM KHACHHANG,HOADON 
WHERE KHACHHANG.MAKH=HOADON.MAKH AND HOADON.NGHD ='2011/1/1'
--bai9
SELECT SOHD,TRIGIA 
FROM HOADON,NHANVIEN 
WHERE NHANVIEN.MANV=HOADON.MANV  AND NHANVIEN.HOTEN='NGUYEN VAN B' AND HOADON.NGHD='2010/10/28'
--bai10
SELECT SP.MASP,SP.TENSP 
FROM SANPHAM SP,HOADON HD,CTHD CT,KHACHHANG KH 
WHERE SP.MASP=CT.MASP AND CT.SOHD=HD.SOHD AND HD.MAKH=KH.MAKH AND KH.HOTEN='NGUYEN VAN A' AND YEAR(HD.NGHD)=2010 AND MONTH(HD.NGHD)=10
--b11
SELECT SOHD 
FROM CTHD WHERE MASP IN ('BB01', 'BB02')
--bai12
SELECT SOHD FROM CTHD 
WHERE (MASP ='BB01' or MASP= 'BB02') and SL between 10 and 20
--bai13
SELECT SOHD FROM CTHD 
WHERE (MASP ='BB01' AND MASP= 'BB02') and SL between 10 and 20
--bai14
SELECT SANPHAM.MASP,SANPHAM.TENSP 
FROM SANPHAM,HOADON,CTHD 
WHERE SANPHAM.NUOCSX='TRUNG QUOC' AND CTHD.SOHD=HOADON.SOHD OR HOADON.NGHD='2011/1/1'
--bai15
SELECT SANPHAM.MASP,SANPHAM.TENSP
FROM SANPHAM 
WHERE SANPHAM.MASP  NOT IN (SELECT CTHD.MASP FROM CTHD)
